apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speech2text
spec:
  destination:
    name: ''
    namespace: speech2text
    server: 'https://kubernetes.default.svc'
  source:
    path: deploy/speech2text
    repoURL: 'https://github.com/glroland/speech2text.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
